
services:
  mongo:
    image: mongo:6.0.4
    restart: unless-stopped
    container_name: MDL2024-mongo
    volumes:
      - .docker/mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - .data/mongo:/data/db
      - .data/log:/var/log/mongodb/
    environment:
      MONGO_INITDB_DATABASE: users
      MONGO_INITDB_ROOT_USERNAME: 'root'
      MONGO_INITDB_ROOT_PASSWORD: 'secret'
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express:1.0.0-alpha
    restart: unless-stopped
    container_name: MDL2024-expresMongo
    environment:
      ME_CONFIG_MONGODB_SERVER: 'mongo'
      ME_CONFIG_MONGODB_ADMINUSERNAME: 'root'
      ME_CONFIG_MONGODB_ADMINPASSWORD: 'secret'
      ME_CONFIG_MONGODB_PORT: '27017'
      ME_CONFIG_BASICAUTH_USERNAME: 'sa'
      ME_CONFIG_BASICAUTH_PASSWORD: 'sa'
    links:
      - mongo
    ports:
      - "8081:8081"